name: Release new version

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  version:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate new version
        uses: pier-oliviert/actions@latest
        with:
          entrypoint: bun run index.ts
          args: create version
          auth_token: "${{ secrets.GITHUB_TOKEN }}"
          repo: "$${{ github.repository}}"
          owner: "$${{ github.owner}}"
          variable: "PHONEBOOK_VERSION"

  changelog:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Changelog
        uses: pier-oliviert/actions@latest
        with:
          entrypoint: bun run index.ts
          args: create changelogs
          auth_token: "${{ secrets.GITHUB_TOKEN }}"
          repo: "$${{ github.repository}}"
          owner: "$${{ github.owner}}"
          variable: "PHONEBOOK_VERSION"

  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Helm package
        uses: pier-oliviert/actions@latest
        with:
          entrypoint: bun run index.ts
          args: create release
          auth_token: "${{ secrets.GITHUB_TOKEN }}"
          repo: "$${{ github.repository}}"
          owner: "$${{ github.owner}}"
          variable: "PHONEBOOK_VERSION"

  helm:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Helm package
        uses: pier-oliviert/actions@latest
        with:
          entrypoint: bun run index.ts
          args: create changelogs
          auth_token: "${{ secrets.GITHUB_TOKEN }}"
          repo: "$${{ github.repository}}"
          owner: "$${{ github.owner}}"
          variable: "PHONEBOOK_VERSION"
